%% Load files
warning('off', 'MATLAB:table:ModifiedAndSavedVarnames');
fileName = "G:/Shared drives/000_College/Rosales Lab/Cleaned up Code/CellProperties18_TestImg.csv";
mSVM4loc = 'G:\Shared drives\000_College\Rosales Lab\Cleaned up Code\mSVM4.mat';
load(mSVM4loc);
oCSV = readtable(fileName);
%% Prep oCSV for predictions
if any(strcmp(oCSV.Properties.VariableNames,'Minkowski_BouligandDimension'))
    oCSV = renamevars(oCSV, ["Minkowski_BouligandDimension",...
        "MeanPearson_sRWhole","MeanPearson_sR16x16",...
        "MeanPearson_sR32x32", "MeanPearson_sR4x4", ...
        "MeanPearson_sR64x64", "MeanPearson_sR8x8"],...
        ["MinkowskiBouligandDimension", "MeanPearsonsRWhole", ...
        "MeanPearsonsR16x16", "MeanPearsonsR32x32", "MeanPearsonsR4x4", ...
        "MeanPearsonsR64x64", "MeanPearsonsR8x8"]);
end
blanks = zeros(height(oCSV), 1);
oCSV = addvars(oCSV, blanks, blanks, blanks, blanks, ...
    blanks, blanks, blanks,...
    'NewVariableNames', {'PredEns10', 'PredMKNN3', 'PredMLR4',...
    'PredMSVM3', 'UMAP1D', 'UMAP2DX', 'UMAP2DY'});
%% Do the SVM predictions
oCSV.PredMSVM4 = trainedSVM4_final.predictFcn(oCSV);
oCSV = removevars(oCSV, {'PredEns10', 'PredMKNN3', 'PredMLR4',...
    'PredMSVM3', 'UMAP1D', 'UMAP2DX', 'UMAP2DY'});
%% Write results back to the original CSV
writetable(oCSV, fileName);
disp(strcat("Saved predictions to: ", fileName));